openapi: 3.0.0

#    After generating the file from the schema, please replace all occurrences of __root__ with field_value to ensure the code runs correctly.

info:
  title: VDJbase API
  version: 2.0.0
  contact:
    name: William Lees
    email: william@lees.org.uk
  description: Public API for VDJbase holding AIRR-seq and Genomic data.
servers:
  - url: http://127.0.0.1:5000/api_v1
    description: OGRDB API
    variables:
      basePath:
        default: api_v1

components:
  schemas:
    # The response object for species lists
    species_response:
      type: object
      properties:
        species:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/release-1.5/specs/airr-schema-openapi3.yaml#/Ontology'
        
    # The response object for datasets
    datasets_response:
      type: object
      properties:
        datasets:
          type: array
          items:
            type: object
            properties:
              dataset:
                type: string        # Name of the dataset in VDJbase
              locus:
                type: string        # The locus it represents (todo: should be an enum)
              type:
                type: string        # Genomic or AIRRseq (todo: should be an enum)
    
    # the response object for subjects and samples within a dataset
    subject_dataset_response:
          type: object
          properties:
            subject_datasets:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string        # The sample ID within VDJbase
                  study_name:
                    type: string        # The study name, eg PRJEB26509 (MiAIRR study.study_id)
                  subject_identifier:  
                    type: string        # The subject ID as defined by the submitter of the study, unique within the study (MiAIRR subhect.subject_id)
                  sample_identifier:
                    type: string        # Sample ID assigned by submitter, unique within study. (MiAIRR sample.sample_id)
                  dataset:
                    type: string        # The VDJbase dataset (e.g. IGH)
            
    # the response object for sample metadata
    sample_genotype_response:
      type: object
      properties:
        Repertoire: 
          $ref: './Genotype.yaml#/Genotype'

    # the response object for sample metadata
    sample_metadata_response:
      type: object
      properties:
        Repertoire: 
          $ref: './Repertoire.yaml#/Repertoire'

    # error response
    error_response:
      type: object
      properties:
        message:
          type: string
          description: Detail about the error

# todo: add two additional routes for AKC:
# - list all datasets in VDJbase (together with species, locus and revision date)
# - provide metadata and genotypes for all samples included in a set of datasets (specify dataset as species, locus, dataset name)

paths:
  /{type}/species:
    get:
      summary: List species with datasets
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
      responses:
        '200':
          description: A list of the available species.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/species_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /{type}/datasets/{species}:
    get:
      summary: List datasets for a species
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string            # todo: should be ontology
      responses:
        '200':
          description: A list of the available datasets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/datasets_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'

  /{type}/subjects/{species}/{dataset}:
    get:
      summary: List subjects and samples in a dataset
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string            # todo: should be ontology
        - name: dataset
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase dataset name
      responses:
        '200':
          description: A list of subjects and samples in the specified dataset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subject_dataset_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
                
  /{type}/sample_genotype/{species}/{dataset}/{subject}/{sample}:
    get:
      summary: Return the genotype for the sample
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string         # todo: should be ontology
        - name: dataset
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase dataset name
        - name: subject
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase subject name
        - name: sample
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase sample name
      responses:
        '200':
          description: A list of subjects and samples in the specified dataset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sample_genotype_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
                
  /{type}/sample_metadata/{species}/{dataset}/{subject}/{sample}:
    get:
      summary: Return the MiAIRR metadata for the sample
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: [airrseq, genomic]
        - name: species
          in: path
          required: true
          schema:
            type: string         # todo: should be ontology
        - name: dataset
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase dataset name
        - name: subject
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase subject name
        - name: sample
          in: path
          required: true
          schema:
            type: string
          description: The VDJbase sample name
      responses:
        '200':
          description: A list of subjects and samples in the specified dataset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sample_metadata_response'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_response'
                
